apiVersion: v1
kind: Service
metadata:  
  name: postgresql-srv
  namespace: next
spec:
  selector:    
    app: next-db-edms
  type: NodePort
  ports:  
  - name: db
    port: 5432
    targetPort: 5432
    nodePort: 30036
    protocol: TCP
